kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands:
      - dotnet sonarscanner begin /k:"easv-devops_week-8_AY3giDC0EVvRW2O60EKU" /d:sonar.host.url="http://sonar.setgo.dk:9000" /d:sonar.token=$$SONAR_TOKEN /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token=$$SONAR_TOKEN
